---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
    driver_config:
      box: geerlingguy/centos6

suites:
  - name: default
    run_list:
      - recipe[chef-splunk-forwarder::default]
    attributes:
